Make the prettier too check all yaml files on macOS-based runners.
The file .markdownlint-cli2.yaml was being overlooked on macOS because of its dot prefix, despite failing our Linux-based CI.

For what it's worth, I first tried a "more clever" pattern but that caused a different failure:

ably-common % npm run lint

> ably-common@1.2.0 lint
> npm-run-all format:*:check

> ably-common@1.2.0 format:js-code:check
> eslint --max-warnings=0 .

> ably-common@1.2.0 format:data:check
> prettier --check **/{.*,*}.{json,yml,yaml}

Checking formatting...
[error] No files matching the pattern were found: "**/.*.yml".
All matched files use Prettier code style!
ERROR: "format:data:check" exited with 2.
?1